menu:
- {name: 'Home', url: '/'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/HyeongminMoon'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/hyeongmin-moon-09aaa3164/'}

contacts:
- {name: 'Hyeongmin Moon', title: 'AI Engineer', department: 'Computer Vision', institution: 'Vitasoft', institution_address: 'Guro, Seoul', phone: '(+82) 10-9407-3526', email: 'mohomin123@gmail.com'}
